name: "Setup YARA environment"
description: "Setup a user-defined YARA version. Executable and compiler only; no yara-python."
author: "ch0mler"
inputs:
  rules:
    description: "Directory of YARA rules to attempt to compile. Single filenames also accepted, Defaults to the current directory"
    required: false
    default: "."
  flags:
    description: "Flags to pass to the YARA compiler. Defaults to just the '--recursive' flag"
    required: false
    default: "--recursive"
  yara-version:
    description: "YARA version to use"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.yara-version }}
