name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs:
  version:
    description: 'YARA version to use'
    default: '3'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
