name: "Setup YARA environment"
description: "Setup a user-defined YARA version. Executable and compiler only; no yara-python."
author: "ch0mler"
inputs:
  yara-version:
    description: "YARA version to use"
    default: "3.10.0"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.yara-version }}
