name: setup-yara

on: [push, pull_request]

jobs:
  major_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: |
        echo 'rule dummy {condition: false}' > ${GITHUB_WORKSPACE}/dummy.yara
    - uses: ./
      with:
        yara-version: "3"
        rules: "dummy.yar"
  minor_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: |
        echo 'rule dummy {condition: false}' > ${GITHUB_WORKSPACE}/dummy.yara
    - uses: ./
      with:
        yara-version: "3.6"
        rules: "dummy.yar"
  patch_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: |
        echo 'rule dummy {condition: false}' > ${GITHUB_WORKSPACE}/dummy.yara
    - uses: ./
      with:
        yara-version: "2.0.0"
        rules: "dummy.yar"
