name: setup-yara

on: [push, pull_request]

jobs:
  install_yara:
    strategy:
      matrix:
        # yaraVersion: [ "4", "3.10.0", "3.6", "2", "1.7.1" ]
        yaraVersion: [ "3.10.0", "3.6", "2" ]
    name: YARA v${{ matrix.yaraVersion }}
    runs-on: ubuntu-latest
    steps:
    # get a copy of the local repository
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    # use the local version of this action
    - uses: ./
      with:
        yaraVersion: ${{ matrix.yaraVersion }}
    # finally, we should be able to access YARA
    - run: /usr/local/bin/yara -v
